// Mocks generated by Mockito 5.1.0 from annotations
// in cinta_film/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:convert' as _i16;
import 'dart:typed_data' as _i17;

import 'package:cinta_film/common/failure.dart' as _i7;
import 'package:cinta_film/data/datasources/db/database_helper.dart' as _i14;
import 'package:cinta_film/data/datasources/film/movie_local_data_source.dart'
    as _i12;
import 'package:cinta_film/data/datasources/film/movie_remote_data_source.dart'
    as _i10;
import 'package:cinta_film/data/models/movie_detail_model.dart' as _i3;
import 'package:cinta_film/data/models/movie_model.dart' as _i11;
import 'package:cinta_film/data/models/movie_table.dart' as _i13;
import 'package:cinta_film/domain/entities/film.dart' as _i8;
import 'package:cinta_film/domain/entities/movie_detail.dart' as _i9;
import 'package:cinta_film/domain/repositories/movie_repository.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailResponse_1 extends _i1.Fake
    implements _i3.MovieDetailResponse {}

class _FakeResponse_2 extends _i1.Fake implements _i4.Response {}

class _FakeStreamedResponse_3 extends _i1.Fake implements _i4.StreamedResponse {
}

/// A class which mocks [RepositoryFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepositoryFilm extends _i1.Mock implements _i5.RepositoryFilm {
  MockRepositoryFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>> filmTayangSaatIni() =>
      (super.noSuchMethod(Invocation.method(#filmTayangSaatIni, []),
          returnValue: Future<_i2.Either<_i7.Failure, List<_i8.Film>>>.value(
              _FakeEither_0<_i7.Failure, List<_i8.Film>>())) as _i6
          .Future<_i2.Either<_i7.Failure, List<_i8.Film>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>>
      ambilDataFilmTerPopuler() =>
          (super.noSuchMethod(Invocation.method(#ambilDataFilmTerPopuler, []),
                  returnValue:
                      Future<_i2.Either<_i7.Failure, List<_i8.Film>>>.value(
                          _FakeEither_0<_i7.Failure, List<_i8.Film>>()))
              as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>>
      ambilFilmRatingTerbaik() =>
          (super.noSuchMethod(Invocation.method(#ambilFilmRatingTerbaik, []),
                  returnValue:
                      Future<_i2.Either<_i7.Failure, List<_i8.Film>>>.value(
                          _FakeEither_0<_i7.Failure, List<_i8.Film>>()))
              as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, _i9.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i7.Failure, _i9.MovieDetail>>.value(
              _FakeEither_0<_i7.Failure, _i9.MovieDetail>())) as _i6
          .Future<_i2.Either<_i7.Failure, _i9.MovieDetail>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i7.Failure, List<_i8.Film>>>.value(
              _FakeEither_0<_i7.Failure, List<_i8.Film>>())) as _i6
          .Future<_i2.Either<_i7.Failure, List<_i8.Film>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>> cariFilm(String? query) =>
      (super.noSuchMethod(Invocation.method(#cariFilm, [query]),
          returnValue: Future<_i2.Either<_i7.Failure, List<_i8.Film>>>.value(
              _FakeEither_0<_i7.Failure, List<_i8.Film>>())) as _i6
          .Future<_i2.Either<_i7.Failure, List<_i8.Film>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> daftarTonton(
          _i9.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#daftarTonton, [film]),
              returnValue: Future<_i2.Either<_i7.Failure, String>>.value(
                  _FakeEither_0<_i7.Failure, String>()))
          as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> removewatchlist(
          _i9.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
              returnValue: Future<_i2.Either<_i7.Failure, String>>.value(
                  _FakeEither_0<_i7.Failure, String>()))
          as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<bool> isAddedTowatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedTowatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Film>>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
          returnValue: Future<_i2.Either<_i7.Failure, List<_i8.Film>>>.value(
              _FakeEither_0<_i7.Failure, List<_i8.Film>>())) as _i6
          .Future<_i2.Either<_i7.Failure, List<_i8.Film>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i10.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i11.MovieModel>> filmTayangSaatIni() => (super.noSuchMethod(
          Invocation.method(#filmTayangSaatIni, []),
          returnValue: Future<List<_i11.MovieModel>>.value(<_i11.MovieModel>[]))
      as _i6.Future<List<_i11.MovieModel>>);
  @override
  _i6.Future<List<_i11.MovieModel>> ambilDataFilmTerPopuler() =>
      (super.noSuchMethod(Invocation.method(#ambilDataFilmTerPopuler, []),
              returnValue:
                  Future<List<_i11.MovieModel>>.value(<_i11.MovieModel>[]))
          as _i6.Future<List<_i11.MovieModel>>);
  @override
  _i6.Future<List<_i11.MovieModel>> ambilFilmRatingTerbaik() =>
      (super.noSuchMethod(Invocation.method(#ambilFilmRatingTerbaik, []),
              returnValue:
                  Future<List<_i11.MovieModel>>.value(<_i11.MovieModel>[]))
          as _i6.Future<List<_i11.MovieModel>>);
  @override
  _i6.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1()))
          as _i6.Future<_i3.MovieDetailResponse>);
  @override
  _i6.Future<List<_i11.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i11.MovieModel>>.value(<_i11.MovieModel>[]))
          as _i6.Future<List<_i11.MovieModel>>);
  @override
  _i6.Future<List<_i11.MovieModel>> cariFilm(String? query) =>
      (super.noSuchMethod(Invocation.method(#cariFilm, [query]),
              returnValue:
                  Future<List<_i11.MovieModel>>.value(<_i11.MovieModel>[]))
          as _i6.Future<List<_i11.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i12.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> insertwatchlist(_i13.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlist, [film]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> removewatchlist(_i13.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i13.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i13.MovieTable?>.value())
          as _i6.Future<_i13.MovieTable?>);
  @override
  _i6.Future<List<_i13.MovieTable>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
              returnValue:
                  Future<List<_i13.MovieTable>>.value(<_i13.MovieTable>[]))
          as _i6.Future<List<_i13.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i14.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i15.Database?>.value())
          as _i6.Future<_i15.Database?>);
  @override
  _i6.Future<int> insertwatchlist(_i13.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlist, [film]),
          returnValue: Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> removewatchlist(_i13.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
          returnValue: Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i6.Future<Map<String, dynamic>?>);
  @override
  _i6.Future<List<Map<String, dynamic>>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i17.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i17.Uint8List>.value(_i17.Uint8List(0)))
          as _i6.Future<_i17.Uint8List>);
  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_3()))
          as _i6.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
